# Generated by Django 4.2.4 on 2023-12-07 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0004_remove_exercise_day_remove_week_plan_delete_day_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Day",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan",
                        to="core.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Week",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weeks",
                        to="api.plan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("sets", models.IntegerField()),
                ("reps", models.IntegerField()),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="api.day",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="day",
            name="week",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="days",
                to="api.week",
            ),
        ),
    ]
