# Generated by Django 4.2.4 on 2023-11-22 03:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_profile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="goals",
            new_name="goal",
        ),
    ]
