# Generated by Django 4.2.4 on 2023-12-07 02:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_rename_goals_profile_goal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="day",
        ),
        migrations.RemoveField(
            model_name="week",
            name="plan",
        ),
        migrations.DeleteModel(
            name="Day",
        ),
        migrations.DeleteModel(
            name="Exercise",
        ),
        migrations.DeleteModel(
            name="Plan",
        ),
        migrations.DeleteModel(
            name="Week",
        ),
    ]
